server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    client_max_body_size 2m;

    location /api/auth/ { proxy_pass http://auth:8000/api/auth/; proxy_set_header Host $host; }
    location /api/users { proxy_pass http://auth:8000/api/users; proxy_set_header Host $host; }
    location /api/roles { proxy_pass http://auth:8000/api/roles; proxy_set_header Host $host; }

    location /api/catalogo/ { proxy_pass http://catalogo:8000/api/catalogo/; proxy_set_header Host $host; }
    location /api/pedidos { proxy_pass http://pedidos:8000/api/pedidos; proxy_set_header Host $host; }
    location /api/pagos { proxy_pass http://pagos:8000/api/pagos; proxy_set_header Host $host; }
    location /api/metodos-pago { proxy_pass http://pagos:8000/api/metodos-pago; proxy_set_header Host $host; }

    location / { try_files $uri $uri/ /index.html; }
}
