server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    location /api/auth/ { proxy_pass http://auth:8000/api/auth/; proxy_set_header Host $host; }
    location /api/users { proxy_pass http://auth:8000/api/users; proxy_set_header Host $host; }
    location /api/roles { proxy_pass http://auth:8000/api/roles; proxy_set_header Host $host; }
    location /api/catalog/ { proxy_pass http://catalog:8000/api/catalog/; proxy_set_header Host $host; }
    location /api/orders { proxy_pass http://orders:8000/api/orders; proxy_set_header Host $host; }
    location /api/payments { proxy_pass http://payments:8000/api/payments; proxy_set_header Host $host; }
    location /api/payment-methods { proxy_pass http://payments:8000/api/payment-methods; proxy_set_header Host $host; }

    location / { try_files $uri $uri/ /index.html; }
}
